on: 
  push:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: davidfekke/helloaction@v1
      with:
        who-to-greet: 'Mona the Jaxnode'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
